graph TB

    subgraph Other
        google_project_service_required_apis[🔧 Required_Apis]
    end

    %% Dependencies

    %% Styling
    style google_project_service_required_apis fill:#607d8b,stroke:#333,color:#fff