name: PR Review with Gemini

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  review:
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && 
       contains(github.event.comment.body, '@gemini-cli /review'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gemini CLI PR Review
        uses: google-github-actions/run-gemini-cli@v0.1.13
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          gemini_model: 'gemini-2.0-flash'
          prompt: |
            Review this pull request for:
            1. Terraform best practices
            2. GCP resource configuration correctness
            3. Test coverage adequacy
            4. Security concerns
            5. Code quality and maintainability
            
            Provide constructive feedback with specific suggestions.
